services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: items
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: go_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASS: 123
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: items
    depends_on:
      - mariadb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
